export const TaxTypeCodeClassification = [
    { code: 'A', codeName: "A-EX", description: "A-EX" },
    { code: "B", codeName: "B-18.00%", description: "B-18.00%" },
    { code: "C", codeName: "C", description: "C" },
    { code: "D", codeName: "D", description: "D" }
];

export const TaxPayerStatusCodeClassification = [
    { code: "A", codeName: "Active", description: "Active" },
    { code: "D", codeName: "Discard", description: "Discard" },
];

export const ProductTypeCodeClassification = [
    { code: 1, codeName: "Raw Material", description: "Raw Material" },
    { code: 2, codeName: "Finished Product", description: "Finished Product" },
    { code: 3, codeName: "Service", description: "Service without stock" },
];

export const PackagingUnitCodeClassification = [
    { code: "AM", codeName: "Ampoule", description: "Ampoule" },
    { code: "BA", codeName: "Barrel", description: "Barrel" },
    { code: "BC", codeName: "Bottlecrate", description: "Bottlecrate" },
    { code: "BE", codeName: "Bundle", description: "Bundle" },
    { code: "BF", codeName: "Balloon, non-protected", description: "Balloon, non-protected" },
    { code: "BG", codeName: "Bag", description: "Bag" },
    { code: "BJ", codeName: "Bucket", description: "Bucket" },
    { code: "BK", codeName: "Basket", description: "Basket" },
    { code: "BL", codeName: "Bale", description: "Bale" },
    { code: "BQ", codeName: "Bottle, protected cylindrical", description: "Bottle, protected cylindrical" },
    { code: "BR", codeName: "Bar", description: "Bar" },
    { code: "BV", codeName: "Bottle, bulbous", description: "Bottle, bulbous" },
    { code: "BZ", codeName: "Bag", description: "Bag" },
    { code: "CA", codeName: "Can", description: "Can" },
    { code: "CH", codeName: "Chest", description: "Chest" },
    { code: "CJ", codeName: "Coffin", description: "Coffin" },
    { code: "CL", codeName: "Coil", description: "Coil" },
    { code: "CR", codeName: "Wooden Box, Wooden Case", description: "Wooden Box, Wooden Case" },
    { code: "CS", codeName: "Cassette", description: "Cassette" },
    { code: "CT", codeName: "Carton", description: "Carton" },
    { code: "CTN", codeName: "Container", description: "Container" },
    { code: "CY", codeName: "Cylinder", description: "Cylinder" },
    { code: "DR", codeName: "Drum", description: "Drum" },
    { code: "GT", codeName: "Extra Countable Item", description: "Extra Countable Item" },
    { code: "HH", codeName: "Hand Baggage", description: "Hand Baggage" },
    { code: "IZ", codeName: "Ingots", description: "Ingots" },
    { code: "JR", codeName: "Jar", description: "Jar" },
    { code: "JU", codeName: "Jug", description: "Jug" },
    { code: "JY", codeName: "Jerry CAN Cylindrical", description: "Jerry CAN Cylindrical" },
    { code: "KZ", codeName: "Canester", description: "Canester" },
    { code: "LZ", codeName: "Logs, in bundle/bunch/truss", description: "Logs, in bundle/bunch/truss" },
    { code: "NT", codeName: "Net", description: "Net" },
    { code: "OU", codeName: "Non-Exterior Packaging Unit", description: "Non-Exterior Packaging Unit" },
    { code: "PD", codeName: "Poddon", description: "Poddon" },
    { code: "PG", codeName: "Plate", description: "Plate" },
    { code: "PI", codeName: "Pipe", description: "Pipe" },
    { code: "PO", codeName: "Pilot", description: "Pilot" },
    { code: "PU", codeName: "Traypack", description: "Traypack" },
    { code: "RL", codeName: "Reel", description: "Reel" },
    { code: "RO", codeName: "Roll", description: "Roll" },
    { code: "RZ", codeName: "Rods, in bundle/bunch/truss", description: "Rods, in bundle/bunch/truss" },
    { code: "SK", codeName: "Skeletoncase", description: "Skeletoncase" },
    { code: "TY", codeName: "Tank, cylindrical", description: "Tank, cylindrical" },
    { code: "VG", codeName: "Bulk, gas (at 1031 mbar 15°C)", description: "Bulk, gas (at 1031 mbar 15°C)" },
    { code: "VL", codeName: "Bulk, liquid (at normal temperature/pressure)", description: "Bulk, liquid (at normal temperature/pressure)" },
    { code: "VO", codeName: "Bulk, solid, large particles (nodules)", description: "Bulk, solid, large particles (nodules)" },
    { code: "VQ", codeName: "Bulk, gas (liquefied at abnormal temperature/pressure)", description: "Bulk, gas (liquefied at abnormal temperature/pressure)" },
    { code: "VR", codeName: "Bulk, solid, granular particles (grains)", description: "Bulk, solid, granular particles (grains)" },
    { code: "VT", codeName: "Extra Bulk Item", description: "Extra Bulk Item" },
    { code: "VY", codeName: "Bulk, fine particles (powder)", description: "Bulk, fine particles (powder)" },
    { code: "ML", codeName: "Mills cigarette", description: "Mills cigarette" },
    { code: "TN", codeName: "TAN 1TAN REFER TO 20BAGS", description: "TAN 1TAN REFER TO 20BAGS" },
];


export const UnitOfQuantityCodeClassification = [
    { code: "4B", codeName: "Pair", description: "Pair" },
    { code: "AV", codeName: "Cap", description: "Cap" },
    { code: "BA", codeName: "Barrel", description: "Barrel" },
    { code: "BE", codeName: "Bundle", description: "Bundle" },
    { code: "BG", codeName: "Bag", description: "Bag" },
    { code: "BL", codeName: "Block", description: "Block" },
    { code: "BLL", codeName: "BLL Barrel", description: "BLL Barrel (petroleum) (158.987 dm³)" },
    { code: "BX", codeName: "Box", description: "Box" },
    { code: "CA", codeName: "Can", description: "Can" },
    { code: "CEL", codeName: "Cell", description: "Cell" },
    { code: "CMT", codeName: "Centimetre", description: "Centimetre" },
    { code: "CR", codeName: "Carat", description: "Carat" },
    { code: "DR", codeName: "Drum", description: "Drum" },
    { code: "DZ", codeName: "Dozen", description: "Dozen" },
    { code: "GLL", codeName: "Gallon", description: "Gallon" },
    { code: "GRM", codeName: "Gram", description: "Gram" },
    { code: "GRO", codeName: "Gross", description: "Gross" },
    { code: "KG", codeName: "Kilo-Gramme", description: "Kilo-Gramme" },
    { code: "KTM", codeName: "Kilometre", description: "Kilometre" },
    { code: "KWT", codeName: "Kilowatt", description: "Kilowatt" },
    { code: "L", codeName: "Litre", description: "Litre" },
    { code: "LBR", codeName: "Pound", description: "Pound" },
    { code: "LK", codeName: "Link", description: "Link" },
    { code: "LTR", codeName: "Litre", description: "Litre" },
    { code: "M", codeName: "Metre", description: "Metre" },
    { code: "M2", codeName: "Square Metre", description: "Square Metre" },
    { code: "M3", codeName: "Cubic Metre", description: "Cubic Metre" },
    { code: "MGM", codeName: "Milligram", description: "Milligram" },
    { code: "MTR", codeName: "Metre", description: "Metre" },
    { code: "MWT", codeName: "Megawatt Hour (1000 kW·h)", description: "Megawatt Hour (1000 kW·h)" },
    { code: "NO", codeName: "Number", description: "Number" },
    { code: "NX", codeName: "Part per Thousand", description: "Part per Thousand" },
    { code: "PA", codeName: "Packet", description: "Packet" },
    { code: "PG", codeName: "Plate", description: "Plate" },
    { code: "PR", codeName: "Pair", description: "Pair" },
    { code: "RL", codeName: "Reel", description: "Reel" },
    { code: "RO", codeName: "Roll", description: "Roll" },
    { code: "SET", codeName: "Set", description: "Set" },
    { code: "ST", codeName: "Sheet", description: "Sheet" },
    { code: "TNE", codeName: "Tonne (Metric Ton)", description: "Tonne (Metric Ton)" },
    { code: "TU", codeName: "Tube", description: "Tube" },
    { code: "U", codeName: "Pieces/Item [Number]", description: "Pieces/Item [Number]" },
    { code: "YRD", codeName: "Yard", description: "Yard" },
];



export const CurrencyCodeClassification = [
    { code: "AED", codeName: "United Arab Emirates dirham", description: "United Arab Emirates dirham" },
    { code: "AFN", codeName: "Afghan afghani", description: "Afghan afghani" },
    { code: "ALL", codeName: "Albanian lek", description: "Albanian lek" },
    { code: "AMD", codeName: "Armenian dram", description: "Armenian dram" },
    { code: "ANG", codeName: "Netherlands Antillean guilder", description: "Netherlands Antillean guilder" },
    { code: "AOA", codeName: "Angolan kwanza", description: "Angolan kwanza" },
    { code: "ARS", codeName: "Argentine peso", description: "Argentine peso" },
    { code: "AUD", codeName: "Australian dollar", description: "Australian dollar" },
    { code: "AWG", codeName: "Aruban florin", description: "Aruban florin" },
    { code: "AZN", codeName: "Azerbaijani manat", description: "Azerbaijani manat" },
    { code: "BAM", codeName: "Bosnia and Herzegovina convertible mark", description: "Bosnia and Herzegovina convertible mark" },
    { code: "BBD", codeName: "Barbados dollar", description: "Barbados dollar" },
    { code: "BDT", codeName: "Bangladeshi taka", description: "Bangladeshi taka" },
    { code: "BGN", codeName: "Bulgarian lev", description: "Bulgarian lev" },
    { code: "BHD", codeName: "Bahraini dinar", description: "Bahraini dinar" },
    { code: "BIF", codeName: "Burundian franc", description: "Burundian franc" },
    { code: "BMD", codeName: "Bermudian dollar", description: "Bermudian dollar" },
    { code: "BND", codeName: "Brunei dollar", description: "Brunei dollar" },
    { code: "BOB", codeName: "Boliviano", description: "Boliviano" },
    { code: "BOV", codeName: "Bolivian Mvdol (funds code)", description: "Bolivian Mvdol (funds code)" },
    { code: "BRL", codeName: "Brazilian real", description: "Brazilian real" },
    { code: "BSD", codeName: "Bahamian dollar", description: "Bahamian dollar" },
    { code: "BTN", codeName: "Bhutanese ngultrum", description: "Bhutanese ngultrum" },
    { code: "BWP", codeName: "Botswana pula", description: "Botswana pula" },
    { code: "BYN", codeName: "New Belarusian ruble", description: "New Belarusian ruble" },
    { code: "BYR", codeName: "Belarusian ruble", description: "Belarusian ruble" },
    { code: "BZD", codeName: "Belize dollar", description: "Belize dollar" },
    { code: "CAD", codeName: "Canadian dollar", description: "Canadian dollar" },
    { code: "CDF", codeName: "Congolese franc", description: "Congolese franc" },
    { code: "CHE", codeName: "WIR Euro (complementary currency)", description: "WIR Euro (complementary currency)" },
    { code: "CHF", codeName: "Swiss franc", description: "Swiss franc" },
    { code: "CHW", codeName: "WIR Franc (complementary currency)", description: "WIR Franc (complementary currency)" },
    { code: "CLF", codeName: "Unidad de Fomento (funds code)", description: "Unidad de Fomento (funds code)" },
    { code: "CLP", codeName: "Chilean peso", description: "Chilean peso" },
    { code: "CNY", codeName: "Chinese yuan", description: "Chinese yuan" },
    { code: "COP", codeName: "Colombian peso", description: "Colombian peso" },
    { code: "COU", codeName: "Unidad de Valor Real (UVR) (funds code)", description: "Unidad de Valor Real (UVR) (funds code)" },
    { code: "CRC", codeName: "Costa Rican colon", description: "Costa Rican colon" },
    { code: "CUC", codeName: "Cuban convertible peso", description: "Cuban convertible peso" },
    { code: "CUP", codeName: "Cuban peso", description: "Cuban peso" },
    { code: "CVE", codeName: "Cape Verde escudo", description: "Cape Verde escudo" },
    { code: "CZK", codeName: "Czech koruna", description: "Czech koruna" },
    { code: "DJF", codeName: "Djiboutian franc", description: "Djiboutian franc" },
    { code: "DKK", codeName: "Danish krone", description: "Danish krone" },
    { code: "DOP", codeName: "Dominican peso", description: "Dominican peso" },
    { code: "DZD", codeName: "Algerian dinar", description: "Algerian dinar" },
    { code: "EGP", codeName: "Egyptian pound", description: "Egyptian pound" },
    { code: "ERN", codeName: "Eritrean nakfa", description: "Eritrean nakfa" },
    { code: "ETB", codeName: "Ethiopian birr", description: "Ethiopian birr" },
    { code: "EUR", codeName: "Euro", description: "Euro" },
    { code: "FJD", codeName: "Fiji dollar", description: "Fiji dollar" },
    { code: "FKP", codeName: "Falkland Islands pound", description: "Falkland Islands pound" },
    { code: "GBP", codeName: "Pound sterling", description: "Pound sterling" },
    { code: "GEL", codeName: "Georgian lari", description: "Georgian lari" },
    { code: "GHS", codeName: "Ghanaian cedi", description: "Ghanaian cedi" },
    { code: "GIP", codeName: "Gibraltar pound", description: "Gibraltar pound" },
    { code: "GMD", codeName: "Gambian dalasi", description: "Gambian dalasi" },
    { code: "GNF", codeName: "Guinean franc", description: "Guinean franc" },
    { code: "GTQ", codeName: "Guatemalan quetzal", description: "Guatemalan quetzal" },
    { code: "GYD", codeName: "Guyanese dollar", description: "Guyanese dollar" },
    { code: "HKD", codeName: "Hong Kong dollar", description: "Hong Kong dollar" },
    { code: "HNL", codeName: "Honduran lempira", description: "Honduran lempira" },
    { code: "HRK", codeName: "Croatian kuna", description: "Croatian kuna" },
    { code: "HTG", codeName: "Haitian gourde", description: "Haitian gourde" },
    { code: "HUF", codeName: "Hungarian forint", description: "Hungarian forint" },
    { code: "IDR", codeName: "Indonesian rupiah", description: "Indonesian rupiah" },
    { code: "ILS", codeName: "Israeli new shekel", description: "Israeli new shekel" },
    { code: "INR", codeName: "Indian rupee", description: "Indian rupee" },
    { code: "IQD", codeName: "Iraqi dinar", description: "Iraqi dinar" },
    { code: "IRR", codeName: "Iranian rial", description: "Iranian rial" },
    { code: "ISK", codeName: "Icelandic króna", description: "Icelandic króna" },
    { code: "JMD", codeName: "Jamaican dollar", description: "Jamaican dollar" },
    { code: "JOD", codeName: "Jordanian dinar", description: "Jordanian dinar" },
    { code: "JPY", codeName: "Japanese yen", description: "Japanese yen" },
    { code: "KES", codeName: "Kenyan shilling", description: "Kenyan shilling" },
    { code: "KGS", codeName: "Kyrgyzstani som", description: "Kyrgyzstani som" },
    { code: "KHR", codeName: "Cambodian riel", description: "Cambodian riel" },
    { code: "KMF", codeName: "Comoro franc", description: "Comoro franc" },
    { code: "KPW", codeName: "North Korean won", description: "North Korean won" },
    { code: "KRW", codeName: "South Korean won", description: "South Korean won" },
    { code: "KWD", codeName: "Kuwaiti dinar", description: "Kuwaiti dinar" },
    { code: "KYD", codeName: "Cayman Islands dollar", description: "Cayman Islands dollar" },
    { code: "KZT", codeName: "Kazakhstani tenge", description: "Kazakhstani tenge" },
    { code: "LAK", codeName: "Lao kip", description: "Lao kip" },
    { code: "LBP", codeName: "Lebanese pound", description: "Lebanese pound" },
    { code: "LKR", codeName: "Sri Lankan rupee", description: "Sri Lankan rupee" },
    { code: "LRD", codeName: "Liberian dollar", description: "Liberian dollar" },
    { code: "LSL", codeName: "Lesotho loti", description: "Lesotho loti" },
    { code: "LYD", codeName: "Libyan dinar", description: "Libyan dinar" },
    { code: "MAD", codeName: "Moroccan dirham", description: "Moroccan dirham" },
    { code: "MDL", codeName: "Moldovan leu", description: "Moldovan leu" },
    { code: "MGA", codeName: "Malagasy ariary", description: "Malagasy ariary" },
    { code: "MKD", codeName: "Macedonian denar", description: "Macedonian denar" },
    { code: "MMK", codeName: "Myanmar kyat", description: "Myanmar kyat" },
    { code: "MNT", codeName: "Mongolian tögrög", description: "Mongolian tögrög" },
    { code: "MOP", codeName: "Macanese pataca", description: "Macanese pataca" },
    { code: "MRO", codeName: "Mauritanian ouguiya", description: "Mauritanian ouguiya" },
    { code: "MUR", codeName: "Mauritian rupee", description: "Mauritian rupee" },
    { code: "MVR", codeName: "Maldivian rufiyaa", description: "Maldivian rufiyaa" },
    { code: "MWK", codeName: "Malawian kwacha", description: "Malawian kwacha" },
    { code: "MXN", codeName: "Mexican peso", description: "Mexican peso" },
    { code: "MXV", codeName: "Mexican Unidad de Inversion (UDI) (funds code)", description: "Mexican Unidad de Inversion (UDI) (funds code)" },
    { code: "MYR", codeName: "Malaysian ringgit", description: "Malaysian ringgit" },
    { code: "MZN", codeName: "Mozambican metical", description: "Mozambican metical" },
    { code: "NAD", codeName: "Namibian dollar", description: "Namibian dollar" },
    { code: "NGN", codeName: "Nigerian naira", description: "Nigerian naira" },
    { code: "NIO", codeName: "Nicaraguan córdoba", description: "Nicaraguan córdoba" },
    { code: "NOK", codeName: "Norwegian krone", description: "Norwegian krone" },
    { code: "NPR", codeName: "Nepalese rupee", description: "Nepalese rupee" },
    { code: "NZD", codeName: "New Zealand dollar", description: "New Zealand dollar" },
    { code: "OMR", codeName: "Omani rial", description: "Omani rial" },
    { code: "PAB", codeName: "Panamanian balboa", description: "Panamanian balboa" },
    { code: "PEN", codeName: "Peruvian sol", description: "Peruvian sol" },
    { code: "PGK", codeName: "Papua New Guinean kina", description: "Papua New Guinean kina" },
    { code: "PHP", codeName: "Philippine peso", description: "Philippine peso" },
    { code: "PKR", codeName: "Pakistani rupee", description: "Pakistani rupee" },
    { code: "PLN", codeName: "Polish złoty", description: "Polish złoty" },
    { code: "PYG", codeName: "Paraguayan guaraní", description: "Paraguayan guaraní" },
    { code: "QAR", codeName: "Qatari riyal", description: "Qatari riyal" },
    { code: "RON", codeName: "Romanian leu", description: "Romanian leu" },
    { code: "RSD", codeName: "Serbian dinar", description: "Serbian dinar" },
    { code: "RUB", codeName: "Russian ruble", description: "Russian ruble" },
    { code: "RWF", codeName: "Rwandan franc", description: "Rwandan franc" },
    { code: "SAR", codeName: "Saudi riyal", description: "Saudi riyal" },
    { code: "SBD", codeName: "Solomon Islands dollar", description: "Solomon Islands dollar" },
    { code: "SCR", codeName: "Seychelles rupee", description: "Seychelles rupee" },
    { code: "SDG", codeName: "Sudanese pound", description: "Sudanese pound" },
    { code: "SEK", codeName: "Swedish krona/kronor", description: "Swedish krona/kronor" },
    { code: "SGD", codeName: "Singapore dollar", description: "Singapore dollar" },
    { code: "SHP", codeName: "Saint Helena pound", description: "Saint Helena pound" },
    { code: "SLL", codeName: "Sierra Leonean leone", description: "Sierra Leonean leone" },
    { code: "SOS", codeName: "Somali shilling", description: "Somali shilling" },
    { code: "SRD", codeName: "Surinamese dollar", description: "Surinamese dollar" },
    { code: "SSP", codeName: "South Sudanese pound", description: "South Sudanese pound" },
    { code: "STD", codeName: "São Tomé and Príncipe dobra", description: "São Tomé and Príncipe dobra" },
    { code: "SVC", codeName: "Salvadoran colón", description: "Salvadoran colón" },
    { code: "SYP", codeName: "Syrian pound", description: "Syrian pound" },
    { code: "SZL", codeName: "Swazi lilangeni", description: "Swazi lilangeni" },
    { code: "THB", codeName: "Thai baht", description: "Thai baht" },
    { code: "TJS", codeName: "Tajikistani somoni", description: "Tajikistani somoni" },
    { code: "TMT", codeName: "Turkmenistani manat", description: "Turkmenistani manat" },
    { code: "TND", codeName: "Tunisian dinar", description: "Tunisian dinar" },
    { code: "TOP", codeName: "Tongan paʻanga", description: "Tongan paʻanga" },
    { code: "TRY", codeName: "Turkish lira", description: "Turkish lira" },
    { code: "TTD", codeName: "Trinidad and Tobago dollar", description: "Trinidad and Tobago dollar" },
    { code: "TWD", codeName: "New Taiwan dollar", description: "New Taiwan dollar" },
    { code: "TZS", codeName: "Tanzanian shilling", description: "Tanzanian shilling" },
    { code: "UAH", codeName: "Ukrainian hryvnia", description: "Ukrainian hryvnia" },
    { code: "UGX", codeName: "Ugandan shilling", description: "Ugandan shilling" },
    { code: "USD", codeName: "United States dollar", description: "United States dollar" },
    { code: "USN", codeName: "United States dollar (next day) (funds code)", description: "United States dollar (next day) (funds code)" },
    { code: "UYI", codeName: "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)", description: "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)" },
    { code: "UYU", codeName: "Uruguayan peso", description: "Uruguayan peso" },
    { code: "UZS", codeName: "Uzbekistan som", description: "Uzbekistan som" },
    { code: "VEF", codeName: "Venezuelan bolívar", description: "Venezuelan bolívar" },
    { code: "VND", codeName: "Vietnamese dong", description: "Vietnamese dong" },
    { code: "VUV", codeName: "Vanuatu vatu", description: "Vanuatu vatu" },
    { code: "WST", codeName: "Samoan tala", description: "Samoan tala" },
    { code: "XAF", codeName: "CFA franc BEAC", description: "CFA franc BEAC" },
    { code: "XAG", codeName: "Silver (one troy ounce)", description: "Silver (one troy ounce)" },
    { code: "XAU", codeName: "Gold (one troy ounce)", description: "Gold (one troy ounce)" },
    { code: "XBA", codeName: "European Composite Unit (EURCO) (bond market unit)", description: "European Composite Unit (EURCO) (bond market unit)" },
    { code: "XBB", codeName: "European Monetary Unit (E.M.U.-6) (bond market unit)", description: "European Monetary Unit (E.M.U.-6) (bond market unit)" },
    { code: "XBC", codeName: "European Unit of Account 9 (E.U.A.-9) (bond market unit)", description: "European Unit of Account 9 (E.U.A.-9) (bond market unit)" },
    { code: "XBD", codeName: "European Unit of Account 17 (E.U.A.-17) (bond market unit)", description: "European Unit of Account 17 (E.U.A.-17) (bond market unit)" },
    { code: "XCD", codeName: "East Caribbean dollar", description: "East Caribbean dollar" },
    { code: "XDR", codeName: "Special drawing rights", description: "Special drawing rights" },
    { code: "XOF", codeName: "CFA franc BCEAO", description: "CFA franc BCEAO" },
    { code: "XPD", codeName: "Palladium (one troy ounce)", description: "Palladium (one troy ounce)" },
    { code: "XPF", codeName: "CFP franc (franc Pacifique)", description: "CFP franc (franc Pacifique)" },
    { code: "XPT", codeName: "Platinum (one troy ounce)", description: "Platinum (one troy ounce)" },
    { code: "XSU", codeName: "SUCRE", description: "SUCRE" },
    { code: "XTS", codeName: "Code reserved for testing purposes", description: "Code reserved for testing purposes" },
    { code: "XUA", codeName: "ADB Unit of Account", description: "ADB Unit of Account" },
    { code: "XXX", codeName: "No currency", description: "No currency" },
    { code: "YER", codeName: "Yemeni rial", description: "Yemeni rial" },
    { code: "ZAR", codeName: "South African rand", description: "South African rand" },
    { code: "ZMW", codeName: "Zambian kwacha", description: "Zambian kwacha" },
    { code: "ZWL", codeName: "Zimbabwean dollar A/10", description: "Zimbabwean dollar A/10" }
];


export const TransactionTypeCodeClassification = [
    { code: "C", codeName: "Copy", description: "Sales and purchase type : Copy" },
    { code: "N", codeName: "Normal", description: "Sales and purchase type : Normal" },
    { code: "P", codeName: "Proforma", description: "Sales and purchase type : Proforma" },
    { code: "T", codeName: "Training", description: "Sales and purchase type : Training" }
];

export const SalesReceiptTypeCodeClassification = [
    { code: "S", codeName: "Sale", description: "Sale" },
    { code: "R", codeName: "Refund after Sale", description: "Refund after Sale" }
];


export const PaymentMethodCodeClassification = [
    { code: "01", codeName: "CASH", description: "CASH" },
    { code: "02", codeName: "CREDIT", description: "CREDIT" },
    { code: "03", codeName: "CASH/CREDIT", description: "CASH/CREDIT" },
    { code: "04", codeName: "BANK CHECK", description: "BANK CHECK PAYMENT" },
    { code: "05", codeName: "DEBIT&CREDIT CARD", description: "PAYMENT USING CARD" },
    { code: "06", codeName: "MOBILE MONEY", description: "ANY TRANSACTION USING MOBILE MONEY SYSTEM" },
    { code: "07", codeName: "OTHER", description: "OTHER MEANS OF PAYMENT" }
];


export const TransactionProgressCodeClassification = [
    { code: '01', codeName: "Wait for Approval", description: "Wait for Approval" },
    { code: '02', codeName: "Approved", description: "Approved" },
    { code: '03', codeName: "Cancel Requested", description: "Cancel Requested" },
    { code: '04', codeName: "Canceled", description: "Canceled" },
    { code: "05", codeName: "Refunded", description: "Refunded" },
    { code: "06", codeName: "Transferred", description: "Transferred" }
];

export const RegistrationTypeCodeClassification = [
    { code: "A", codeName: "Automatic", description: "Automatic" },
    { code: "M", codeName: "Manual", description: "Manual" }
]

export const PurchaseReceiptTypeCodeClassification = [
    { code: "P", codeName: "Purchase", description: "Purchase" },
    { code: "R", codeName: "Refund after Purchase", description: "Refund after Purchase" }
];

export const StockInOutTypeCodeClassification = [
    { code: "01", codeName: "Import", description: "Incoming-Import" },
    { code: "02", codeName: "Purchase", description: "Incoming-Purchase" },
    { code: "03", codeName: "Return", description: "Incoming-Return" },
    { code: "04", codeName: "Stock Movement", description: "Incoming-Stock Movement" },
    { code: "05", codeName: "Processing", description: "Incoming-Processing" },
    { code: "06", codeName: "Adjustment", description: "Incoming-Adjustment" },
    { code: "11", codeName: "Sale", description: "Outgoing-Sale" },
    { code: "12", codeName: "Return", description: "Outgoing-Return" },
    { code: "13", codeName: "Stock Movement", description: "Outgoing-Stock Movement" },
    { code: "14", codeName: "Processing", description: "Outgoing-Processing" },
    { code: "15", codeName: "Discarding", description: "Outgoing-Discarding" },
    { code: "16", codeName: "Adjustment", description: "Outgoing-Adjustment" }
];

export const RefundReasonCode = [
    { code: "01", codeName: "Missing Quantity", description: "Missing Quantity" },
    { code: "02", codeName: "Missing Item", description: "Missing Item" },
    { code: "03", codeName: "Damaged", description: "Damaged" },
    { code: "04", codeName: "Wasted", description: "Wasted" },
    { code: "05", codeName: "Raw Material Shortage", description: "Raw Material Shortage" },
    { code: "06", codeName: "Refund", description: "Refund" },
    { code: "07", codeName: "Wrong Customer TIN", description: "Wrong Customer TIN" },
    { code: "08", codeName: "Wrong Customer Name", description: "Wrong Customer Name" },
    { code: "09", codeName: "Wrong Amount/price", description: "Wrong Amount/price" },
    { code: "10", codeName: "Wrong Quantity", description: "Wrong Quantity" },
    { code: "11", codeName: "Wrong Item(s)", description: "Wrong Item(s)" },
    { code: "12", codeName: "Wrong tax type", description: "Wrong tax type" },
    { code: "13", codeName: "Other reason", description: "Other reason" }
];



// Item code
// itemCd is mandatory and it has to be unique. In other words, each item has its unique itemCd.
// Below is how item code is generated.
// For example:
// itemCd: RW2NTBA0000012
// RW: Country of Origin (Rwanda)
// 2: Product Type (Finished Product)
// NT: Packaging Unit (NET)
// BA: Quantity Unity (Barrel)
// 0000012: increments from 0000001 to N value